server:
  port: ${port:9091}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5


mybatis:
  type-aliases-package: com.itheima.user.pojo


test:
  name: simonlee
